// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppCard: typeof import('./components/AppCard.vue')['default']
    AppChip: typeof import('./components/AppChip.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppIcon3d: typeof import('./components/AppIcon3d.vue')['default']
    AppLocaleSwitcher: typeof import('./components/AppLocaleSwitcher.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppSkillSearch: typeof import('./components/AppSkillSearch.vue')['default']
    AppSocials: typeof import('./components/AppSocials.vue')['default']
    AppSubtitle: typeof import('./components/AppSubtitle.vue')['default']
    AppTitle: typeof import('./components/AppTitle.vue')['default']
    AppTooltip: typeof import('./components/AppTooltip.vue')['default']
    ContactFormEmail: typeof import('./components/ContactFormEmail.vue')['default']
    ContactFormMessage: typeof import('./components/ContactFormMessage.vue')['default']
    ContactFormName: typeof import('./components/ContactFormName.vue')['default']
    ContactFormPreview: typeof import('./components/ContactFormPreview.vue')['default']
    ContactFormResult: typeof import('./components/ContactFormResult.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IAkarIconsAlignToTop: typeof import('~icons/akar-icons/align-to-top')['default']
    IBiMarkdown: typeof import('~icons/bi/markdown')['default']
    IFeatherArrowLeft: typeof import('~icons/feather/arrow-left')['default']
    IFeatherArrowRight: typeof import('~icons/feather/arrow-right')['default']
    IFeatherGithub: typeof import('~icons/feather/github')['default']
    IFeatherInstagram: typeof import('~icons/feather/instagram')['default']
    IFeatherLinkedin: typeof import('~icons/feather/linkedin')['default']
    IFeatherSend: typeof import('~icons/feather/send')['default']
    IFeatherTwitter: typeof import('~icons/feather/twitter')['default']
    IIcRoundCheckBox: typeof import('~icons/ic/round-check-box')['default']
    IIcRoundCheckBoxOutlineBlank: typeof import('~icons/ic/round-check-box-outline-blank')['default']
    ITwemojiFlagPoland: typeof import('~icons/twemoji/flag-poland')['default']
    ITwemojiFlagSpain: typeof import('~icons/twemoji/flag-spain')['default']
    ITwemojiFlagUnitedKingdom: typeof import('~icons/twemoji/flag-united-kingdom')['default']
    Logo: typeof import('./components/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionContact: typeof import('./components/SectionContact.vue')['default']
    SectionHi: typeof import('./components/SectionHi.vue')['default']
    SectionSkills: typeof import('./components/SectionSkills.vue')['default']
  }
}

export {}
